name: Test distributable validator

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install package
        run: python -m pip install .
      - name: Test package
        run: python -m unittest discover -s tests -p 'test_ter.py'
      - name: Test CLI
        run: |
          ter --version
          ter check-update
